Ellibrary/Ellibrary.App.Web/Models/BookModel.cs
using Ellibrary.App.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ellibrary.App.Web.Models
{
    public class BookModel
    {
        public ICollection<Book> Books { get; set; }
    }
}

Ellibrary/Ellibrary.App.Web/Models/CommercialModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Ellibrary.Service.Commercial.Entities;

namespace Ellibrary.App.Web.Models
{
    public class CommercialModel
    {
        public ICollection<Commerc> Commercials { get; set; }

    }
}

Ellibrary/Ellibrary.App.Web/Models/NavigationModel.cs
using Ellibrary.App.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ellibrary.App.Web.Models
{
    public class NavigationModel
    {
        public ICollection<Category> Categories { get; set; }
    }
}

Ellibrary/Ellibrary.App.Web/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ellibrary.App.Business.Interfaces;
using Ellibrary.App.Web.Models;
using Ellibrary.App.General.Logger;
using Ellibrary.App.General.Logger.Interfaces;
using Ellibrary.App.Data;

namespace Ellibrary.App.Web.Controllers
{
    public class BookController : Controller
    {
        private IBookRepository _repository;
        private ILoggers _logger;        

        
        public BookController(IBookRepository repository, ILoggers logger)
        {
            if (repository == null||logger==null)
            {
                throw new NullReferenceException();
            }
            _repository = repository;
            _logger=logger;
        }
        
        public ActionResult Main()
        {
           BookModel model = new BookModel{Books = _repository.Items.ToList() };
           return View(model);
        }

        public ActionResult GetBooksByCategory(int categoryID)
        {
            BookModel model = new BookModel { Books = _repository.GetBooksByCategory(categoryID) };

            _logger.InfoFormat("Elements by categoryID: " + categoryID, null);

            return View("Main", model);
        }



        public ActionResult GetBookByID(int bookID)
        {
            var model = _repository.GetBookByID(bookID);
            
            _logger.InfoFormat("Get ad by adID: "+bookID, null);

            return View("BookInfo", model);
        }        
    }
}

Ellibrary/Ellibrary.App.Web/Controllers/CommercialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ellibrary.App.Web.Models;
using Ellibrary.Service.Commercial;

namespace Ellibrary.App.Web.Controllers
{
    public class CommercialController : Controller
    {
        private ICommercialRepository commercialRepository;

        public CommercialController(ICommercialRepository commercialRepository)
        {
            this.commercialRepository = commercialRepository ?? throw new NullReferenceException();
        }

        public PartialViewResult GetCommercial()
        {           

            var commercials = commercialRepository.GetCommercials();
            var model = new CommercialModel
            {
                Commercials = commercials
            };

            return PartialView("CommercialPartial", model);
        }

        public PartialViewResult GetCommercialVertical()
        {

            var commercials = commercialRepository.GetCommercials();
            var model = new CommercialModel
            {
                Commercials = commercials
            };

            return PartialView("VerticalCommercialPartial", model);
        }


    }
}

Ellibrary/Ellibrary.App.Web/Controllers/ErrorController.cs
using Ellibrary.App.General.Logger.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace Ellibrary.App.Web.Controllers
{
    public class ErrorController : Controller
    {
        private ILoggers _logger;
        public ErrorController(ILoggers logger)
        {
            if (logger == null)
            {
                throw new NullReferenceException(nameof(logger));
            }
            _logger = logger;
        }

        public ActionResult Index(string errorMessage)
        {
            _logger?.ErrorFormat(errorMessage);
            return View("Error");
        }

        public ActionResult BadRequest()
        {
            Response.StatusCode = 400;
            return View("BadRequest");
        }

        public ActionResult PageNotFound()
        {
            Response.StatusCode = 404;
            return View("NotFoundPage");
        }

        public ActionResult ServerNotResponding()
        {
            Response.StatusCode = 500;
            return View("ServerNotRespondingPage");
        }
    }
}

Ellibrary/Ellibrary.App.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace Ellibrary.App.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Ellibrary/Ellibrary.App.Web/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ellibrary.App.Business.Interfaces;
using Ellibrary.App.Web.Models;

namespace Ellibrary.App.Web.Controllers
{
    public class NavigationController : Controller
    {
        private ICategoryRepository _repository;

        public NavigationController(ICategoryRepository repository)
        {
            if (repository == null)
            {
                throw new NullReferenceException();
            }
            _repository = repository;
        }



        public PartialViewResult Nav()
        {
            NavigationModel model = new NavigationModel{ Categories = _repository.GetCategories()};
            return PartialView(model);
        }

        public PartialViewResult Getsubcategories(int categoryID)
        {
            NavigationModel model = new NavigationModel { Categories = _repository.GetSubcategories(categoryID) };
            return PartialView("SubcategoryPartial", model);
        }

        public PartialViewResult MainNav()
        {
            return PartialView();
        }

    }
}

Ellibrary/Ellibrary.App.Web/Views/Book/BookImagesPartial.cshtml
@model ICollection<Ellibrary.App.Data.Image>
@using Ellibrary.App.Web.Helpers

<table>
    
        @foreach (var item in Model)
        { 
           <tr>
                <td>
                    @Html.RenderImage(item.Data, item.Extension, null, new { width = 300, height = 200,style="float:left; display:inline;" })
                </td>
            </tr>
      }       
</table>

Ellibrary/Ellibrary.App.Web/Views/Book/BookInfo.cshtml
@model Ellibrary.App.Data.Book
@{ Layout = null;}


<table cellpadding="0" align="center" cellspacing="10">
    <tr valign="top">
        <td>
            @{Html.RenderPartial("BookImagesPartial", model: Model.Image); }
        </td>

        <td>
            <table cellpadding="0">
                    <tr><td>Name: @Model.Name</td></tr>

                        <tr>
                            <td>
                                <table style="display:inline" cellpadding="0">
                                    <tr>
                                        <td>
                                            Categories:
                                            @{
                                                List<string> categories = new List<string>();
                                                foreach (var item in Model.Category)
                                                {
                                                    categories.Add(item.Name);
                                                    categories.Add(",   ");
                                                }
                                                categories.RemoveAt(categories.Count - 1);
                                            }
                                            @foreach (var item in categories)
                                            {
                                                @item
                                            }
                                        </td>
                                    </tr>
                                </table>
                            </td>
                    </tr>

                    <tr> 
                        <td>
                            <table style="display:inline" cellpadding="0">
                                <tr>
                                    <td>
                                        Authors:
                                        @{
                                            List<string> authors = new List<string>();
                                            foreach (var item in Model.Author)
                                            {
                                                authors.Add(item.FIO);
                                                authors.Add(",   ");
                                            }
                                            authors.RemoveAt(authors.Count - 1);
                                        }
                                        @foreach (var item in authors)
                                {
                                            @item
                                        }
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <tr><td>Yaer of publishing: @Model.YearOfPublishing</td></tr>

                    <tr><td>Language: @Model.Lang</td></tr>

                    <tr><td>Publishing: @Model.Publishing.Name</td></tr>

                    <tr><td>Link: @Html.ActionLink(Model.Link, null)</td></tr>
                </table>
           </td>
    </tr>
</table>

Ellibrary/Ellibrary.App.Web/Views/Book/BookPartial.cshtml
@model Ellibrary.App.Data.Book

@Html.ActionLink(Model.Name, "GetBookByID", "Book", routeValues: new { bookID = Model.BookID }, htmlAttributes: new { @class = "links" })
 

Ellibrary/Ellibrary.App.Web/Views/Book/Main.cshtml
@model Ellibrary.App.Web.Models.BookModel
@using Ellibrary.App.Web.Helpers

@{Layout = "~/Views/Shared/BookPageLayout.cshtml"; }

<table style="width:auto;padding:0px 20px 20px 20px; display:inline-block; margin-right:200px;">
    <tr valign="top" >
        <td width="400px;">
            @{ Html.RenderAction("Nav", "Navigation"); }
            @{Html.RenderAction("GetCommercialVertical","Commercial");}

        </td>
        <td>
            <table>
                @foreach (var item in Model.Books)
                {
                    <tr valign="top" >
                        <td class="bookview">
                            <p>
                                @Html.RenderImage(item.Image.Select(x=>x.Data).First(), item.Image.Select(x => x.Extension).First(), null, new { width = 250, height = 150, style = "float:left; display:inline;" })
                                @Ajax.ActionLink(item.Name, "GetBookByID", "Book",
                               routeValues: new { bookID=item.BookID }, ajaxOptions: new AjaxOptions { UpdateTargetId = "details-container" },
                               htmlAttributes: new { @class = "links" })
                            </p>
                        </td>
                    </tr>
                }
            </table>
        </td>  
        
    </tr>
</table>
<table id="details-container" style="position:fixed; display:inline-block;" ></table>

Ellibrary/Ellibrary.App.Web/Views/Commercial/CommercialPartial.cshtml
@model Ellibrary.App.Web.Models.CommercialModel
@using Ellibrary.App.Web.Helpers

<br>
<table>
    <tr>
@foreach (var item in Model.Commercials)
{
    <td>
        @Html.RenderImage(item.Image.Data, item.Image.Extension, null, new { width = 400, height = 300 })
    </td>
}
   </tr>
</table>

Ellibrary/Ellibrary.App.Web/Views/Commercial/VerticalCommercialPartial.cshtml
@model Ellibrary.App.Web.Models.CommercialModel
@using Ellibrary.App.Web.Helpers

<br>
<table>    
        @foreach (var item in Model.Commercials)
        {
            <tr>
                <td>
                    @Html.RenderImage(item.Image.Data, item.Image.Extension, null, new { width =220, height = 150 })
                </td>
            </tr>
        }           
</table>

Ellibrary/Ellibrary.App.Web/Views/Home/About.cshtml
<h1 style="text-align:center;">The main information about site</h1>

Ellibrary/Ellibrary.App.Web/Views/Home/BookInfo.cshtml
@model Ellibrary.App.Data.Book

@Html.ActionLink("Back", "Index", "Home")<br>

<div>Name: @Model.Name</div>



<div> 
    <table style="display:inline">
        <tr>Authors: </tr>
        @{
            foreach(var item in Model.Author)
            {
                <tr>
                    <td> @item.FIO </td>                    
                </tr>
            }
        }        
    </table>        
</div>

<div>Yaer of publishing: @Model.YearOfPublishing</div>

<div>Language: @Model.Lang</div>

<div>Publishing: @Model.Publishing.Name</div>

<div>Link: @Model.Link</div>

Ellibrary/Ellibrary.App.Web/Views/Navigation/MainNav.cshtml
<table class="mainnav" style="width:99%;">
    <tr>
        <th class="mainlable">
            @Html.ActionLink("ELLIBRARY", "Index", "Home", null, new { style = "font-size:30px;text-decoration: none;" })
        </th>
        <th class="navlinks">
            @Html.ActionLink("Books", "Main", "Book",null, htmlAttributes: new { @class = "links" })
        </th>
        <th class="navlinks">
            @Html.ActionLink("About", "About", "Home",null, htmlAttributes: new { @class = "links" })
        </th>        
        <th></th>
    </tr>
</table><br>

Ellibrary/Ellibrary.App.Web/Views/Navigation/Nav.cshtml
@model Ellibrary.App.Web.Models.NavigationModel

<table class="categories" style="width:auto;">
    <tr valign="top">
        <td>
            <table>
                @foreach (var item in Model.Categories)
                {
                    <tr valign="top">
                        <th class="categ">
                           @Html.ActionLink(item.Name, "GetBooksByCategory", "Book", routeValues: new { categoryID = item.CategoryID }, htmlAttributes: new { @class = "links" })
                            <table id="subcategories-container-@item.CategoryID" style="font-size:14px; width:100%;" align="center"></table>
                        </th>
                        <th class="tosubcat">
                            @Ajax.ActionLink(">", "Getsubcategories", "Navigation",
                           routeValues: new { categoryID = item.CategoryID },
                           ajaxOptions: new AjaxOptions { UpdateTargetId = "subcategories-container-"+item.CategoryID.ToString() },
                           htmlAttributes: new { @class = "links"})
                        </th>
                    </tr>
                }
            </table>
        </td>
    </tr>
</table><br>

Ellibrary/Ellibrary.App.Web/Views/Navigation/SubcategoryPartial.cshtml
@model Ellibrary.App.Web.Models.NavigationModel

@{
    if (Model.Categories != null)
    {
        foreach (var item in Model.Categories)
        {
            <tr valign="top">
                <th class="subcateg">
                  @Html.ActionLink(item.Name, "GetBooksByCategory", "Book", routeValues: new { categoryID = item.CategoryID }, htmlAttributes: new { @class = "links" })                  
                </th>
            </tr>
        }
    }
}                

Ellibrary/Ellibrary.App.Web/Views/Shared/BookPageLayout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ellibrary</title>
    <link rel="stylesheet" type="text/css" href="/Content/css/MainStyle.css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

</head>
<body class="backgr">
    <div>
        @{ Html.RenderAction("MainNav", "Navigation"); }
    </div>
    <div style="background-color:white; width:95%; margin:50px 5px 30px 30px; padding:5px 5px 0px 0px;" >
        <div>
            @RenderBody()
        </div>
    </div>
</body>
</html>

Ellibrary/Ellibrary.App.Web/Views/Shared/BookPartial.cshtml
@model Ellibrary.App.Data.Book

@Html.ActionLink(Model.Name, "GetBookByID", "Book", routeValues: new { bookID = Model.BookID }, htmlAttributes: new { @class="links"})    

Ellibrary/Ellibrary.App.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ellibrary</title>
    <link rel="stylesheet" type="text/css" href="/Content/css/MainStyle.css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

</head>
<body class="backgr">
    <div>
        @{ Html.RenderAction("MainNav", "Navigation"); }
    </div>
    <div style="background-color:white; width:95%; margin:50px 5px 30px 30px; padding:5px 5px 0px 0px;" align="center">
        <div >
            @RenderBody()
        </div>
        <div>
            @{ Html.RenderAction("GetCommercial", "Commercial"); }
        </div>
    </div>
</body>
</html>